name: COLORS_SOK_2B

on:
  workflow_dispatch:

jobs:
  bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install discord.py

      - run: python bot.py
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          OWNER_USER_ID: ${{ secrets.OWNER_USER_ID }}
          OWNER_CODE: ${{ secrets.OWNER_CODE }}
