name: Product Game Bot

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  bot:

    runs-on: ubuntu-latest

    timeout-minutes: 360

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade Pip
        run: |
          python -m pip install --upgrade pip

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Verify Files
        run: |
          ls -la
          test -f bot.py
          test -f config.json
          test -f servers.json
          test -f images_api.json
          test -f sessions.json
          test -f products_cache.json

      - name: Run Bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          OWNER_USER_ID: ${{ secrets.OWNER_USER_ID }}
          OWNER_CODE: ${{ secrets.OWNER_CODE }}

        run: |
          python bot.py
